# pid - Ui_drawing_info_ctrl
# 2020/1/31 - 23:24
# Copyright 2020 Wang D.Q <Wang D.Q@PyCharm>
# !/venv python
# -*- coding: utf-8 -*-

# import sys
from PyQt5.QtCore import *
# from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
# from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets

from UI.Ui_drawing_info import Ui_Dialog_drawing_info
from func.handle_drawing_database import Handle_drawing_database

database_address = str("D:/GitHub/pid/data/drawings.xlsx").replace("\\", "/")

class Dialog_drawing_info_ctrl(QDialog,Ui_Dialog_drawing_info):
    @pyqtSlot()
    def __init__(self, signal_drawing_no, parent=None):
        super(Dialog_drawing_info_ctrl, self).__init__(parent)
        self.handle_drawing_info = Handle_drawing_database(database_address)
        self.drawing_info = self.handle_drawing_info.read_drawing_info(signal_drawing_no['drawing_no'])
        self.setupUi(self)
        self.checkBox_info_changabilty.stateChanged.connect(lambda: self.info_changabilty_checked(self.checkBox_info_changabilty))

        print(signal_drawing_no)
        self.show()
        self.take_slot_drawing_no()
        # self.buttonBox.accepted.connect(lambda: self.buttonBox_accepted)
        # TODO: REBUILD THE LINEEDITS

    ''' -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- '''
    def take_slot_drawing_no(self):
        # TODO: FUNCTION RENAME
        self.lineEdit_drawing_no.setText(str(self.drawing_info['drawing_no']))
        self.lineEdit_database_series_no.setText(str(self.drawing_info['database_series_no']))
        self.lineEdit_drawing_title.setText(str(self.drawing_info['drawing_title']))
        self.lineEdit_profession.setText(str(self.drawing_info['profession']))
        self.lineEdit_vol_title.setText(str(self.drawing_info['vol_title']))
        self.lineEdit_drawing_integrity.setText(str(self.drawing_info['drawing_integrity']))
        self.lineEdit_release_stage.setText(str(self.drawing_info['release_stage']))
        self.lineEdit_review_status.setText(str(self.drawing_info['review_status']))
        self.lineEdit_planned_release_date.setText(str(self.drawing_info['planned_release_date']))

    def info_changabilty_checked(self, btn):
        self.lineEdit_drawing_no.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_database_series_no.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_drawing_title.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_profession.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_profession_subvol.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_drawing_integrity.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_release_stage.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_review_status.setReadOnly(self.checkBox_info_changabilty.isChecked())
        self.lineEdit_planned_release_date.setReadOnly(self.checkBox_info_changabilty.isChecked())

    ''' -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- '''
    def buttonBox_accepted(self):
        self.close()
    ''' -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- -*- '''

    def setupUi(self, Dialog_drawing_info):
        Dialog_drawing_info.setObjectName("Dialog_drawing_info")
        Dialog_drawing_info.resize(787, 272)
        Dialog_drawing_info.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_drawing_info)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_info_changabilty = QtWidgets.QCheckBox(Dialog_drawing_info)
        self.checkBox_info_changabilty.setChecked(True)
        self.checkBox_info_changabilty.setObjectName("checkBox_info_changabilty")
        self.gridLayout.addWidget(self.checkBox_info_changabilty, 0, 0, 1, 1)
        self.label_drawing_no = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_drawing_no.setObjectName("label_drawing_no")
        self.gridLayout.addWidget(self.label_drawing_no, 1, 0, 1, 1)
        self.lineEdit_drawing_no = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_drawing_no.setAutoFillBackground(False)
        self.lineEdit_drawing_no.setText("")
        self.lineEdit_drawing_no.setDragEnabled(False)
        self.lineEdit_drawing_no.setReadOnly(True)
        self.lineEdit_drawing_no.setObjectName("lineEdit_drawing_no")
        self.gridLayout.addWidget(self.lineEdit_drawing_no, 1, 1, 1, 1)
        self.label_database_series_no = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_database_series_no.setObjectName("label_database_series_no")
        self.gridLayout.addWidget(self.label_database_series_no, 1, 2, 1, 1)
        self.lineEdit_database_series_no = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_database_series_no.setText("")
        self.lineEdit_database_series_no.setReadOnly(True)
        self.lineEdit_database_series_no.setObjectName("lineEdit_database_series_no")
        self.gridLayout.addWidget(self.lineEdit_database_series_no, 1, 3, 1, 1)
        self.label_drawing_title = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_drawing_title.setObjectName("label_drawing_title")
        self.gridLayout.addWidget(self.label_drawing_title, 2, 0, 1, 1)
        self.lineEdit_drawing_title = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_drawing_title.setText("")
        self.lineEdit_drawing_title.setReadOnly(True)
        self.lineEdit_drawing_title.setObjectName("lineEdit_drawing_title")
        self.gridLayout.addWidget(self.lineEdit_drawing_title, 2, 1, 1, 3)
        self.label_profession = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_profession.setObjectName("label_profession")
        self.gridLayout.addWidget(self.label_profession, 3, 0, 1, 1)
        self.lineEdit_profession = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_profession.setText("")
        self.lineEdit_profession.setReadOnly(True)
        self.lineEdit_profession.setObjectName("lineEdit_profession")
        self.gridLayout.addWidget(self.lineEdit_profession, 3, 1, 1, 1)
        self.label_vol_title = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_vol_title.setObjectName("label_vol_title")
        self.gridLayout.addWidget(self.label_vol_title, 3, 2, 1, 1)
        self.lineEdit_vol_title = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_vol_title.setText("")
        self.lineEdit_vol_title.setReadOnly(True)
        self.lineEdit_vol_title.setObjectName("lineEdit_vol_title")
        self.gridLayout.addWidget(self.lineEdit_vol_title, 3, 3, 1, 1)
        self.label_release_status = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_release_status.setObjectName("label_release_status")
        self.gridLayout.addWidget(self.label_release_status, 4, 0, 1, 1)
        self.lineEdit_drawing_integrity = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_drawing_integrity.setText("")
        self.lineEdit_drawing_integrity.setReadOnly(True)
        self.lineEdit_drawing_integrity.setObjectName("lineEdit_drawing_integrity")
        self.gridLayout.addWidget(self.lineEdit_drawing_integrity, 4, 1, 1, 1)
        self.label_release_stage = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_release_stage.setObjectName("label_release_stage")
        self.gridLayout.addWidget(self.label_release_stage, 4, 2, 1, 1)
        self.lineEdit_release_stage = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_release_stage.setText("")
        self.lineEdit_release_stage.setReadOnly(True)
        self.lineEdit_release_stage.setObjectName("lineEdit_release_stage")
        self.gridLayout.addWidget(self.lineEdit_release_stage, 4, 3, 1, 1)
        self.label_review_status = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_review_status.setObjectName("label_review_status")
        self.gridLayout.addWidget(self.label_review_status, 5, 0, 1, 1)
        self.lineEdit_review_status = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_review_status.setText("")
        self.lineEdit_review_status.setReadOnly(True)
        self.lineEdit_review_status.setObjectName("lineEdit_review_status")
        self.gridLayout.addWidget(self.lineEdit_review_status, 5, 1, 1, 1)
        self.label_planned_release_date = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_planned_release_date.setObjectName("label_planned_release_date")
        self.gridLayout.addWidget(self.label_planned_release_date, 5, 2, 1, 1)
        self.lineEdit_planned_release_date = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_planned_release_date.setText("")
        self.lineEdit_planned_release_date.setReadOnly(True)
        self.lineEdit_planned_release_date.setObjectName("lineEdit_planned_release_date")
        self.gridLayout.addWidget(self.lineEdit_planned_release_date, 5, 3, 1, 1)
        self.label_mark_1 = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_mark_1.setObjectName("label_mark_1")
        self.gridLayout.addWidget(self.label_mark_1, 6, 0, 1, 1)
        self.lineEdit_mark_1 = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_mark_1.setText("")
        self.lineEdit_mark_1.setReadOnly(True)
        self.lineEdit_mark_1.setObjectName("lineEdit_mark_1")
        self.gridLayout.addWidget(self.lineEdit_mark_1, 6, 1, 1, 3)
        self.label_mark_2 = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_mark_2.setObjectName("label_mark_2")
        self.gridLayout.addWidget(self.label_mark_2, 7, 0, 1, 1)
        self.lineEdit_mark_2 = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_mark_2.setText("")
        self.lineEdit_mark_2.setReadOnly(True)
        self.lineEdit_mark_2.setObjectName("lineEdit_mark_2")
        self.gridLayout.addWidget(self.lineEdit_mark_2, 7, 1, 1, 3)
        self.label_mark_3 = QtWidgets.QLabel(Dialog_drawing_info)
        self.label_mark_3.setObjectName("label_mark_3")
        self.gridLayout.addWidget(self.label_mark_3, 8, 0, 1, 1)
        self.lineEdit_mark_3 = QtWidgets.QLineEdit(Dialog_drawing_info)
        self.lineEdit_mark_3.setText("")
        self.lineEdit_mark_3.setReadOnly(True)
        self.lineEdit_mark_3.setObjectName("lineEdit_mark_3")
        self.gridLayout.addWidget(self.lineEdit_mark_3, 8, 1, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_drawing_info)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 3, 1, 1)

        self.retranslateUi(Dialog_drawing_info)
        self.buttonBox.rejected.connect(Dialog_drawing_info.close)
        self.buttonBox.accepted.connect(Dialog_drawing_info.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog_drawing_info)
        Dialog_drawing_info.setTabOrder(self.lineEdit_drawing_no, self.lineEdit_database_series_no)
        Dialog_drawing_info.setTabOrder(self.lineEdit_database_series_no, self.lineEdit_drawing_title)
        Dialog_drawing_info.setTabOrder(self.lineEdit_drawing_title, self.lineEdit_profession)
        Dialog_drawing_info.setTabOrder(self.lineEdit_profession, self.lineEdit_vol_title)
        Dialog_drawing_info.setTabOrder(self.lineEdit_vol_title, self.lineEdit_drawing_integrity)
        Dialog_drawing_info.setTabOrder(self.lineEdit_drawing_integrity, self.lineEdit_release_stage)
        Dialog_drawing_info.setTabOrder(self.lineEdit_release_stage, self.lineEdit_review_status)
        Dialog_drawing_info.setTabOrder(self.lineEdit_review_status, self.lineEdit_planned_release_date)

    def retranslateUi(self, Dialog_drawing_info):
        _translate = QtCore.QCoreApplication.translate
        Dialog_drawing_info.setWindowTitle(_translate("Dialog_drawing_info", "图纸信息"))
        self.checkBox_info_changabilty.setText(_translate("Dialog_drawing_info", "修改锁定"))
        self.label_drawing_no.setText(_translate("Dialog_drawing_info", "图号"))
        self.label_database_series_no.setText(_translate("Dialog_drawing_info", "数据序号"))
        self.label_drawing_title.setText(_translate("Dialog_drawing_info", "施工图卷册名称"))
        self.label_profession.setText(_translate("Dialog_drawing_info", "专业"))
        self.label_vol_title.setText(_translate("Dialog_drawing_info", "专业分卷"))
        self.label_release_status.setText(_translate("Dialog_drawing_info", "出版状态"))
        self.label_release_stage.setText(_translate("Dialog_drawing_info", "出图阶段"))
        self.label_review_status.setText(_translate("Dialog_drawing_info", "审核状态"))
        self.label_planned_release_date.setText(_translate("Dialog_drawing_info", "计划出版日期"))
        self.label_mark_1.setText(_translate("Dialog_drawing_info", "备注1"))
        self.label_mark_2.setText(_translate("Dialog_drawing_info", "备注2"))
        self.label_mark_3.setText(_translate("Dialog_drawing_info", "备注3"))
