# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 398)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_mainwindow = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_mainwindow.setObjectName("tabWidget_mainwindow")
        self.tab_drawings = QtWidgets.QWidget()
        self.tab_drawings.setObjectName("tab_drawings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_drawings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_profession = QtWidgets.QComboBox(self.tab_drawings)
        self.comboBox_profession.setObjectName("comboBox_profession")
        self.gridLayout_2.addWidget(self.comboBox_profession, 0, 0, 1, 1)
        self.pushButton_review_report = QtWidgets.QPushButton(self.tab_drawings)
        self.pushButton_review_report.setObjectName("pushButton_review_report")
        self.gridLayout_2.addWidget(self.pushButton_review_report, 1, 0, 1, 1)
        self.lineEdit_drawing_no_input = QtWidgets.QLineEdit(self.tab_drawings)
        self.lineEdit_drawing_no_input.setObjectName("lineEdit_drawing_no_input")
        self.gridLayout_2.addWidget(self.lineEdit_drawing_no_input, 1, 2, 1, 1)
        self.pushButton_drawing_no_input = QtWidgets.QPushButton(self.tab_drawings)
        self.pushButton_drawing_no_input.setTabletTracking(False)
        self.pushButton_drawing_no_input.setAutoDefault(False)
        self.pushButton_drawing_no_input.setDefault(False)
        self.pushButton_drawing_no_input.setObjectName("pushButton_drawing_no_input")
        self.gridLayout_2.addWidget(self.pushButton_drawing_no_input, 1, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_drawings)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 1, 7)
        self.pushButton_new_review_flow = QtWidgets.QPushButton(self.tab_drawings)
        self.pushButton_new_review_flow.setObjectName("pushButton_new_review_flow")
        self.gridLayout_2.addWidget(self.pushButton_new_review_flow, 0, 3, 1, 1)
        self.spinBox_drawing_qty = QtWidgets.QSpinBox(self.tab_drawings)
        self.spinBox_drawing_qty.setMinimum(1)
        self.spinBox_drawing_qty.setObjectName("spinBox_drawing_qty")
        self.gridLayout_2.addWidget(self.spinBox_drawing_qty, 0, 2, 1, 1)
        self.tabWidget_mainwindow.addTab(self.tab_drawings, "")
        self.tab_specifications = QtWidgets.QWidget()
        self.tab_specifications.setObjectName("tab_specifications")
        self.tabWidget_mainwindow.addTab(self.tab_specifications, "")
        self.gridLayout.addWidget(self.tabWidget_mainwindow, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_mainwindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_review_report.setText(_translate("MainWindow", "图纸送审"))
        self.lineEdit_drawing_no_input.setText(_translate("MainWindow", "C0101"))
        self.pushButton_drawing_no_input.setText(_translate("MainWindow", "Go"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        self.pushButton_new_review_flow.setText(_translate("MainWindow", "新建审查流程"))
        self.tabWidget_mainwindow.setTabText(self.tabWidget_mainwindow.indexOf(self.tab_drawings), _translate("MainWindow", "A"))
        self.tabWidget_mainwindow.setTabText(self.tabWidget_mainwindow.indexOf(self.tab_specifications), _translate("MainWindow", "B"))
