# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_new_review_flow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_new_review_flow(object):
    def setupUi(self, Dialog_new_review_flow):
        Dialog_new_review_flow.setObjectName("Dialog_new_review_flow")
        Dialog_new_review_flow.resize(842, 96)
        Dialog_new_review_flow.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_new_review_flow)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_new_review_flow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 7, 1, 6)
        self.lineEdit_drawing_title_01 = QtWidgets.QLineEdit(Dialog_new_review_flow)
        self.lineEdit_drawing_title_01.setObjectName("lineEdit_drawing_title_01")
        self.gridLayout.addWidget(self.lineEdit_drawing_title_01, 1, 3, 1, 6)
        self.label_date = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_date.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 0, 10, 1, 1)
        self.comboBox_release_stage = QtWidgets.QComboBox(Dialog_new_review_flow)
        self.comboBox_release_stage.setEditable(True)
        self.comboBox_release_stage.setObjectName("comboBox_release_stage")
        self.gridLayout.addWidget(self.comboBox_release_stage, 0, 8, 1, 2)
        self.label_drawing_no_01 = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_drawing_no_01.setObjectName("label_drawing_no_01")
        self.gridLayout.addWidget(self.label_drawing_no_01, 1, 0, 1, 1)
        self.lineEdit_drawing_no_01 = QtWidgets.QLineEdit(Dialog_new_review_flow)
        self.lineEdit_drawing_no_01.setObjectName("lineEdit_drawing_no_01")
        self.gridLayout.addWidget(self.lineEdit_drawing_no_01, 1, 1, 1, 1)
        self.label_release_stage = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_release_stage.setObjectName("label_release_stage")
        self.gridLayout.addWidget(self.label_release_stage, 0, 7, 1, 1)
        self.label_profession = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_profession.setObjectName("label_profession")
        self.gridLayout.addWidget(self.label_profession, 0, 5, 1, 1)
        self.lineEdit_vol_title_01 = QtWidgets.QLineEdit(Dialog_new_review_flow)
        self.lineEdit_vol_title_01.setObjectName("lineEdit_vol_title_01")
        self.gridLayout.addWidget(self.lineEdit_vol_title_01, 1, 10, 1, 3)
        self.label_drawing_title_01 = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_drawing_title_01.setObjectName("label_drawing_title_01")
        self.gridLayout.addWidget(self.label_drawing_title_01, 1, 2, 1, 1)
        self.radioButton_drawing_integrity_01 = QtWidgets.QRadioButton(Dialog_new_review_flow)
        self.radioButton_drawing_integrity_01.setChecked(True)
        self.radioButton_drawing_integrity_01.setObjectName("radioButton_drawing_integrity_01")
        self.gridLayout.addWidget(self.radioButton_drawing_integrity_01, 1, 13, 1, 1)
        self.label_drawing_qty = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_drawing_qty.setObjectName("label_drawing_qty")
        self.gridLayout.addWidget(self.label_drawing_qty, 0, 2, 1, 1)
        self.label_vol_title_01 = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_vol_title_01.setObjectName("label_vol_title_01")
        self.gridLayout.addWidget(self.label_vol_title_01, 1, 9, 1, 1)
        self.label_r1_review_no = QtWidgets.QLabel(Dialog_new_review_flow)
        self.label_r1_review_no.setObjectName("label_r1_review_no")
        self.gridLayout.addWidget(self.label_r1_review_no, 0, 0, 1, 1)
        self.lineEdit_r1_review_no = QtWidgets.QLineEdit(Dialog_new_review_flow)
        self.lineEdit_r1_review_no.setObjectName("lineEdit_r1_review_no")
        self.gridLayout.addWidget(self.lineEdit_r1_review_no, 0, 1, 1, 1)
        self.dateEdit_start_flow = QtWidgets.QDateEdit(Dialog_new_review_flow)
        self.dateEdit_start_flow.setObjectName("dateEdit_start_flow")
        self.gridLayout.addWidget(self.dateEdit_start_flow, 0, 11, 1, 1)
        self.pushButton_qty_minus = QtWidgets.QPushButton(Dialog_new_review_flow)
        self.pushButton_qty_minus.setObjectName("pushButton_qty_minus")
        self.gridLayout.addWidget(self.pushButton_qty_minus, 0, 4, 1, 1)
        self.lineEdit_profession = QtWidgets.QLineEdit(Dialog_new_review_flow)
        self.lineEdit_profession.setReadOnly(False)
        self.lineEdit_profession.setObjectName("lineEdit_profession")
        self.gridLayout.addWidget(self.lineEdit_profession, 0, 6, 1, 1)
        self.pushButton_qty_add = QtWidgets.QPushButton(Dialog_new_review_flow)
        self.pushButton_qty_add.setObjectName("pushButton_qty_add")
        self.gridLayout.addWidget(self.pushButton_qty_add, 0, 3, 1, 1)

        self.retranslateUi(Dialog_new_review_flow)
        self.buttonBox.accepted.connect(Dialog_new_review_flow.accept)
        self.buttonBox.rejected.connect(Dialog_new_review_flow.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog_new_review_flow)
        Dialog_new_review_flow.setTabOrder(self.lineEdit_r1_review_no, self.comboBox_release_stage)
        Dialog_new_review_flow.setTabOrder(self.comboBox_release_stage, self.lineEdit_drawing_no_01)
        Dialog_new_review_flow.setTabOrder(self.lineEdit_drawing_no_01, self.radioButton_drawing_integrity_01)

    def retranslateUi(self, Dialog_new_review_flow):
        _translate = QtCore.QCoreApplication.translate
        Dialog_new_review_flow.setWindowTitle(_translate("Dialog_new_review_flow", "新建审查流程"))
        self.lineEdit_drawing_title_01.setText(_translate("Dialog_new_review_flow", "主厂房布桩图(包括加热器平台桩、汽机底板桩)"))
        self.label_date.setText(_translate("Dialog_new_review_flow", "日期"))
        self.label_drawing_no_01.setText(_translate("Dialog_new_review_flow", "图号1"))
        self.lineEdit_drawing_no_01.setText(_translate("Dialog_new_review_flow", "T0987"))
        self.label_release_stage.setText(_translate("Dialog_new_review_flow", "出图阶段"))
        self.label_profession.setText(_translate("Dialog_new_review_flow", "专业"))
        self.label_drawing_title_01.setText(_translate("Dialog_new_review_flow", "卷册名称"))
        self.radioButton_drawing_integrity_01.setText(_translate("Dialog_new_review_flow", "完整卷册"))
        self.label_drawing_qty.setText(_translate("Dialog_new_review_flow", "图纸册数"))
        self.label_vol_title_01.setText(_translate("Dialog_new_review_flow", "专业分卷"))
        self.label_r1_review_no.setText(_translate("Dialog_new_review_flow", "审查号"))
        self.lineEdit_r1_review_no.setText(_translate("Dialog_new_review_flow", "SC098-09"))
        self.pushButton_qty_minus.setText(_translate("Dialog_new_review_flow", "减一册"))
        self.pushButton_qty_add.setText(_translate("Dialog_new_review_flow", "加一册"))
